#PHYSX_INCLUDE="-I${PHYSX_HOME}/Graphics/include -I${PHYSX_HOME}/LowLevel/API/include -I${PHYSX_HOME}/LowLevel/hlcommon/include -I${PHYSX_HOME}/SDKs/Cooking/include -I${PHYSX_HOME}/SDKs/NxCharacter/include -I${PHYSX_HOME}/Tools/CookedMesh/Reader/include -I${PHYSX_HOME}/Tools/NxuStream2 -I${PHYSX_HOME}/Tools/SoftBody"

OCAMLC=ocamlc
OCAMLOPT=ocamlopt
COMPFLAGS=-ccopt $(CCOPT)
LINKFLAGS=-L/usr/local/lib/ocaml
DEPFLAGS=
CCOPT=

SWIG=swig
SWIG_FLAGS=-ocaml -c++ -w301 -Werror
SWIG_DEFINES=-DNX_CALL_CONV=""
SWIGCO=swig -ocaml -co

LIBDIR=~/projects/ocaml-physx/lib
